import { Award, Copy, Headphones, LogOut, Phone, ShieldCheck, UserRound, WalletCards } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { CustomerShell } from "../components/CustomerShell";
import { Button, Card } from "../components/Ui";
import { money } from "../lib/api";
import { useAuth } from "../lib/auth";

export default function ProfilePage() {
  const { user, logout } = useAuth(); const navigate = useNavigate();
  return <CustomerShell><main className="mx-auto max-w-4xl px-4 py-6 sm:px-6 sm:py-8"><Card className="overflow-hidden"><div className="relative overflow-hidden bg-gradient-to-br from-shopee-500 to-orange-500 p-6 text-white sm:p-9"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full border-[30px] border-white/10" /><div className="relative flex items-center gap-5"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-3xl bg-white text-2xl font-black text-shopee-500 shadow-xl">{user?.displayName.slice(0, 2).toUpperCase()}</div><div><p className="text-xs font-black uppercase tracking-[.18em] text-white/65">Work account</p><h1 className="mt-1 text-3xl font-black">{user?.displayName}</h1><p className="mt-1 text-sm font-semibold text-white/75">@{user?.username}</p></div></div></div><div className="grid gap-3 p-5 sm:grid-cols-3 sm:p-7"><Stat icon={<WalletCards />} label="Balance" value={money(user?.balance ?? 0)} /><Stat icon={<Award />} label="Level" value={user?.level || "STARTER"} /><Stat icon={<ShieldCheck />} label="Tasks completed" value={String(user?.totalOrders ?? 0)} /></div></Card>
    <div className="mt-5 grid gap-4 sm:grid-cols-2"><Card className="p-5"><h2 className="font-black text-slate-900">Account information</h2><div className="mt-4 grid gap-3"><Info icon={<UserRound />} label="Username" value={user?.username || "-"} /><Info icon={<Phone />} label="Phone number" value={user?.phone || "-"} /><Info icon={<ShieldCheck />} label="Referred by" value={user?.referrer?.displayName || "-"} /></div></Card><Card className="p-5"><h2 className="font-black text-slate-900">Quick access</h2><div className="mt-4 grid gap-3"><Link to="/finance" className="flex items-center justify-between rounded-2xl bg-slate-50 p-4 text-sm font-black text-slate-700 hover:bg-shopee-50 hover:text-shopee-600">Manage balance <WalletCards size={18} /></Link><Link to="/support" className="flex items-center justify-between rounded-2xl bg-slate-50 p-4 text-sm font-black text-slate-700 hover:bg-shopee-50 hover:text-shopee-600">Customer support <Headphones size={18} /></Link><Button variant="ghost" onClick={async () => { await logout(); navigate("/login"); }}><LogOut size={18} /> Sign out</Button></div></Card></div>
  </main></CustomerShell>;
}
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-shopee-500 shadow-sm">{icon}</span><div><p className="text-[10px] font-black uppercase tracking-wide text-slate-400">{label}</p><p className="mt-0.5 font-black text-slate-900">{value}</p></div></div>; }
function Info({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-2xl border border-slate-100 p-3"><span className="text-shopee-500">{icon}</span><div className="min-w-0"><p className="text-[10px] font-black uppercase text-slate-400">{label}</p><p className="truncate text-sm font-black text-slate-800">{value}</p></div></div>; }
